---
    environment: production
    chdir: /var/cmdr-server/lib
    address: 127.0.0.1
    user: cmdr
    group: cmdr
    port: 4567
    pid: /var/cmdr-server/tmp/unicorn.pid
    rackup: /var/cmdr-server/lib/config.ru
    log: /var/cmdr-server/log/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true
